### ISSUE TITLE
Mounting suppot

### ISSUE THREAD

**Issue by valsor** [alexedwards/flow#4]
Very nice router! I like it very much.
Have a question. How can I mount multiple sets of routes like `chi.Mount()` does. For example I have some subdomens/components, each with their own routes set. How can I wire them together for passing to main `http.Server`?

**Comment by alexedwards** [comment]
The equivalent of `chi.Mount()` is `Handle()`. You can use it without specifying HTTP methods, like:

```
mux := flow.New()
mux.Handle("/path", yourMountedHandler)
```
