### ISSUE TITLE
any interest in generating the http.Request for the client side?

### ISSUE THREAD

**Issue by marco-m** [alexedwards/flow#7]
Like for example `rata.NewRequestGenerator()`, see https://github.com/tedsuo/rata
If not, how would you suggest implementing the client side of an API?
thanks!

**Comment by alexedwards** [comment]
Hi,

I don't think so, it's not a feature that I can imagine personally using and I'd rather keep this package small and focused.

For the client side of an API, I'd use the regular `http.NewRequest` function from the standard library and construct the URLs manually.
